#!/bin/bash
# Exit on error
set -e

echo "Running build hook !"
TAG_COMMAND="--tag $IMAGE_NAME"

if [[ "$DOCKER_TAG" == *"-"* ]]; then
  # If the current build tag has a version specific number, parse branch / version for image labels
  TAG_BRANCH=$(echo "$DOCKER_TAG" | cut -d '-' -f 1)
  TAG_VERSION=$(echo "$DOCKER_TAG" | cut -d '-' -f 2)
  TAG_COMMAND="$TAG_COMMAND --tag $DOCKER_REPO:$TAG_BRANCH"
  echo "Multi-tagging: $DOCKER_REPO:$TAG_BRANCH & $IMAGE_NAME"
else
  # For image without version (like dev), use default build options
  TAG_BRANCH=$DOCKER_TAG
  TAG_VERSION=${SOURCE_COMMIT:0:8}
  echo "Uni-tagging: $IMAGE_NAME"
fi

echo "Executing build on branch $TAG_BRANCH version $TAG_VERSION using Dockerfile profile $DOCKERFILE_PATH"

# Installing emulators
docker run --privileged --rm tonistiigi/binfmt --install all

# Creating builder to build multi-platform images
docker buildx create --name builder \
             --driver docker-container \
             --platform linux/amd64,linux/arm64 \
             --use

# Building multi-platform images
docker buildx build --platform linux/amd64,linux/arm64 \
             --build-arg TAG="$TAG_BRANCH" \
             --build-arg VERSION="$TAG_VERSION" \
             --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
             --file "$DOCKERFILE_PATH" \
             --progress plain \
             --output "type=image,push=true" \
             $TAG_COMMAND .

echo "Build and push done!"
