#!/bin/bash
# Exit on error
set -e

echo "Running push hook !"

echo "Listing images that were built"
docker images

echo "Pushing every tag for docker repo $DOCKER_REPO"
docker push -a "$DOCKER_REPO"
echo "Push done!"
